### ISSUE TITLE
User Dashboard Page: Populate top-left table total balance for each investment, and equivalent CAD value owned by the user

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#10]

**Comment by ayeshah** [comment]
Use get user balance API: https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#d6326c1f-f061-4f1f-9930-e48228b26dba

**Comment by stevenWang0917** [comment]
Which API link is used for fetch the relationships between investment_id and investment_name?

**Comment by ayeshah** [comment]
@stevenWang0917 Get All Investments API 
https://documenter.getpostman.com/view/1176933/SVSLrU7M?version=latest#b1985de3-13b9-46ac-9268-1f59a33ba1d0
