### ISSUE TITLE
Sign Up Validation

### ISSUE THREAD

**Issue by ayeshah** [MarkdaleMGMT/frontend-app#108]
Improve the signup page so that the form does not allow a user to signup with a username similar to another (i.e. where only the character cases are different, e.g. riskingtime, RiskingTime)

validate signup to confirm the user is signing up with a unique e-mail

**Comment by ayeshah** [comment]
disallow different cases 
unique emails per user 
verification was working for a user with no records of the user in the db

**Comment by RiskingTime** [comment]
allow the user to toggle whether to mask or not mask their password as they are typing it

**Comment by RiskingTime** [comment]
- create same username with multiple cases
- create same username (identical)
- prevent less than 8 digits (strong password)
- doesn't check if its a valid e-mail

**Comment by RiskingTime** [comment]
prevent a user from user the same e-mail as another user
