### ISSUE TITLE
User Dashboard Page: Create Mountain View/ Line Chart View and populate data with the API you have created to get the balance for all investments owned by the user

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#12]
User should be able to toggle between mountain view/ line view

**Comment by ayeshah** [comment]
User User Balance History API: https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#daec7a21-20b6-4a99-82fc-4d97a22a5e6c
