### ISSUE TITLE
User Dashboard Page: Populate transaction history table using API (transaction-methods)

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#13]
Search should allow searching through any of the columns

**Comment by ayeshah** [comment]
User Transaction History API https://restless-rocket-9495.postman.co/collections/1176933-4bce3ef7-e3a8-440f-b3a9-ea8c6e0dc5bc?version=latest&workspace=181f25d6-8baf-4370-8190-90ffeb20acd9#0d2413a4-07ac-4ac8-8645-e1b6b48b9f95

**Comment by ayeshah** [comment]
The table should show the transaction is descending order (i.e. latest transaction first)

When the user enters values on the search field, it should return rows which contain the text in any of the columns. The number of entries shown at once in the table and pagination should be updated when the user changes the Show entries value in the dropdown.

Show entries dropdown can have following values: 10, 25, 50, 100

**Comment by RiskingTime** [comment]
@Dorothy006 investname field should display the correct value
