### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#171]
create a contact page with a form, gets sent to an e-mail (same e-mail as receives the daily backup)

also include links to help documentation (blog pages?)

make the uppercanadacoins@gmail.com the e-mail address displayed on the contact page, but don't hard code it.

the value is probably written to the config.js in the transaction-methods repo

**Comment by sarahsakhri** [comment]
need to create a post request in the backend repo to send email to uppercanadacoins@gmail.com

**Comment by ynjacobs** [comment]
Make button uniform to rest of pages
remove text above form
make dialog boxes same format as other pages
