### ISSUE TITLE
dashboard chart

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#172]
should display the canadian value of investment (with a running value of the currency at each point in time, not a single value of the currency)

**Comment by RiskingTime** [comment]
come next week with a plan to present

**Comment by Zartinad** [comment]
1) https://stackoverflow.com/questions/39643876/find-missing-dates-in-data
2) Fill in missing dates
3) Join with exchange rates
4) CAculate cad balance with running total
