### ISSUE TITLE
functionality gaps due to restart

### ISSUE THREAD

**Issue by ynjacobs** [MarkdaleMGMT/frontend-app#210]
When restarting server or change branch, there are gaps in which functionality is running

**Comment by RiskingTime** [comment]
- exchange rates, error handling with scraping, what happens if data not perfect, what happens no response, etc

- documentation, update the FX functionality page with how to restart the server once the FX configurations are changed in the database

**Comment by RiskingTime** [comment]
- make a command that restarts all servers, to be used when FX configs are changed for example, or any other time the whole program needs a restart

**Comment by Zartinad** [comment]
Global Update works when forced using a get request. However, function is inconistent with crontasks. If days are skipped by global update, the next iteration will account for those missing days
