### ISSUE TITLE
24 hour chart toggle

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#219]
update the chart so that it shows the data from last 24 hours when the toggle is picked
- for exchange page chart
- for dashboard chart
- remove the 24 hour toggle on the investment pages

**Comment by Zartinad** [comment]
-Need to parameterize possible interval options because exchange and investment charts share the same components

**Comment by Zartinad** [comment]
> -Need to parameterize possible interval options because exchange and investment charts share the same components

Could just enable and disable 24 hours options as react boolean prop

**Comment by RiskingTime** [comment]
remove 24 toggle from dashboard chart

**Comment by Zartinad** [comment]
remove 24 from dashboardchart
