### ISSUE TITLE
Freiexchange updates not working

### ISSUE THREAD

**Issue by Zartinad** [MarkdaleMGMT/frontend-app#220]
Freiexchange API has changed. Need to scrape information from the page htmls

**Comment by RiskingTime** [comment]
https://freebitcoins.com/xchange/market/BTC_CLAM

**Comment by RiskingTime** [comment]
document how you add this new exchange as a data source (and remove the old ones) in the FX functionality wiki page (found in the transaction-methods wiki)

**Comment by Zartinad** [comment]
https://freebitcoins.com/xchange/api/ticker/BTC_CLAM
