### ISSUE TITLE
Check scotiabank scrape

### ISSUE THREAD

**Issue by Zartinad** [MarkdaleMGMT/frontend-app#229]

**Comment by RiskingTime** [comment]
Description:https://www.bloomberg.com/quote/CADUSD:CUR 

https://www.xe.com/currencyconverter/convert/?Amount=1&From=CAD&To=USD

https://www.rbcbank.com/cgi-bin/tools/cadusd-foreign-exchange-calculator/start.cgi

**Comment by Zartinad** [comment]
single value indicates mid price

**Comment by RiskingTime** [comment]
https://bylls.com/rates
