### ISSUE TITLE
Exchange Page: Allow users to exchange investments (top form)

### ISSUE THREAD

**Issue by ayeshah** [MarkdaleMGMT/frontend-app#24]
left side: from investment (source)
right side: to investment (target)

The drop-down on the left shows the users all investment names that they own along with the currency. I.e. Clam Miner (CLAM), etc...
The drop-down on the right shows all currencies that are present on the system in the same format <investment_name> (currency)

When the user enters a number on the left input field, it should automatically update the equivalent value in other currency (right input field) -- use Get Rate API  , mid value

When the user presses the exchange button, it should execute the transaction and show a notification on the status of transaction on top of the page (as returned from API) as a toast/snackbar (Exchange Investment API)

https://reactstrap.github.io/components/alerts/

**Comment by sanliverpool13** [comment]
I can't seem to navigate to the exchange page? Only the dashboard page is available. There is no exchange page component in the source code in the 'develop' branch.

**Comment by ayeshah** [comment]
@sanliverpool13 yes you have to add an exchange page to the React Router component
