### ISSUE TITLE
Sign In page: integrate with sign in API with validation

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#3]
Redirect to Dashboard if successful, else return error message

**Comment by baikhuz** [comment]
created Alert component, added actions, reducers, types for signin page and alerts. npm install before testing

**Comment by baikhuz** [comment]
bug: logout on page refresh.

a valid hashed token to store in localStorage needs to be sent from the backend to fix the issue. Frontend API currently does not have this functionality

**Comment by ayeshah** [comment]
@Dorothy006  Make sure response returned from server is shown on the page
