### ISSUE TITLE
Admin Dashboard: Create Mountain View/ Line Chart View and populate data with the balance for all investments on the platform

### ISSUE THREAD

**Issue by ayeshah** [MarkdaleMGMT/frontend-app#36]
User User Balance History API: https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#daec7a21-20b6-4a99-82fc-4d97a22a5e6c 
username: 'investment_user'

User should be able to toggle between mountain view/ line view
Show the investment names as legends at the bottom of the chart

**Comment by RiskingTime** [comment]
should show values in CAD
