### ISSUE TITLE
Sign Up page: validation for each field, redirect to Sign In page if successful, otherwise return appropriate error message

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#4]
validation: no empty fields and email is in a valid format. 
remaining validation is done on server side , server will return an appropriate message

**Comment by ayeshah** [comment]
Link on email verification should redirect to Sign In Page, with a message that email has been verified

**Comment by baikhuz** [comment]
awaiting response on form validation from James to complete the error message part

**Comment by ayeshah** [comment]
validation: no empty fields and email is in a valid format. 
remaining validation is done on server side , server will return an appropriate message
