### ISSUE TITLE
Side Menu: dynamically populate the side menu with each investment using an API

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#6]

**Comment by RiskingTime** [comment]
once the user logs in, they arrive at the dashboard, on the dashboard page, populate the side menu with each investment using an API, do not hard code

**Comment by ayeshah** [comment]
use Get All Investments API: https://documenter.getpostman.com/view/1176933/SVSLrU7M?version=latest#b1985de3-13b9-46ac-9268-1f59a33ba1d0

**Comment by RiskingTime** [comment]
Side menu should show currencies as top level and expand into their investments

**Comment by ayeshah** [comment]
@Dorothy006  side menu should expand
