### ISSUE TITLE
welcome page

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#95]
what to do next?
deposit?
link to what this is all about?

**Comment by ayeshah** [comment]
a  payments page should be displayed, which has a table of investments and deposit / withdrawal button

**Comment by ayeshah** [comment]
A welcome page giving a brief overview of the functionality which the user slides through

**Comment by ayeshah** [comment]
https://react-annotation.susielu.com/

**Comment by ayeshah** [comment]
have a flag for mobile (show/hide)
change formatting for mobile later on
